# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library_api.proto

require 'google/protobuf'

require 'library_api/book'
require 'library_api/responses'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module LibraryAPI
end
