// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: library_api/responses.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Library_API_Responses.pbobjc.h"
 #import "Library_API_Book.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - LibraryAPI_Responses_ResponsesRoot

@implementation LibraryAPI_Responses_ResponsesRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - LibraryAPI_Responses_ResponsesRoot_FileDescriptor

static GPBFileDescriptor *LibraryAPI_Responses_ResponsesRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"LibraryAPI.Responses"
                                                 objcPrefix:@"LibraryAPI_Responses_"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - LibraryAPI_Responses_GetBooks

@implementation LibraryAPI_Responses_GetBooks

@dynamic booksArray, booksArray_Count;

typedef struct LibraryAPI_Responses_GetBooks__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *booksArray;
} LibraryAPI_Responses_GetBooks__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "booksArray",
        .dataTypeSpecific.className = GPBStringifySymbol(LibraryAPI_Book),
        .number = LibraryAPI_Responses_GetBooks_FieldNumber_BooksArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(LibraryAPI_Responses_GetBooks__storage_, booksArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[LibraryAPI_Responses_GetBooks class]
                                     rootClass:[LibraryAPI_Responses_ResponsesRoot class]
                                          file:LibraryAPI_Responses_ResponsesRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(LibraryAPI_Responses_GetBooks__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
