# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library_api/author.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "LibraryAPI.Author" do
    optional :id, :int32, 1
    optional :name, :string, 4
    optional :birthday, :message, 3, "google.protobuf.Timestamp"
  end
end

module LibraryAPI
  Author = Google::Protobuf::DescriptorPool.generated_pool.lookup("LibraryAPI.Author").msgclass
end
