# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library_api/responses.proto

require 'google/protobuf'

require 'library_api/book'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "LibraryAPI.Responses.GetBooks" do
    repeated :books, :message, 1, "LibraryAPI.Book"
  end
end

module LibraryAPI
  module Responses
    GetBooks = Google::Protobuf::DescriptorPool.generated_pool.lookup("LibraryAPI.Responses.GetBooks").msgclass
  end
end
